version: '3'
services:
  node:
    container_name: app
    restart: always
    build: 
      context: .
      dockerfile: deploy/Dockerfile
    ports:
      - 80:3000
    volumes:
      - ./:/code
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db
volumes:
 mongodb:
